### ISSUE TITLE
Preferences

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#225]
A new preferences page with options about the user

### Level
Medium

### Current behavior
- The preferences page is minimal

### Expected behavior
- The preferences as on the screenshot. We already have the model implemented, and this is basically add more fields and setup updates for the user preferences

### Screenshot
![preferences](https://user-images.githubusercontent.com/88840/50368415-ba40a280-0588-11e9-9235-452a44592179.png)

**Comment by alexanmtz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Preferences](https://trello.com/c/7howIRCs/275-preferences)

**Comment by alexanmtz** [comment]
### 🆕 Welcome to Gitpay

Gitpay is an Open Source platform to reward contributors to get thinks done 💝

[About Gitpay platform](https://gitpay.me).

For portuguese, you can [access the portuguese version](first-comment.pt-br.md)

### 📋 Step by Step

- [x] 🔔 ***Issue open*** an issue was created
- [x] 👌 **Issue added on Gitpay** this issue was added on gitpay [{{url}}]({{url}})
- [ ] 📝 **Add bounties** A bounty is added to get things done
- [ ] 📝 **Set a deadline** A deadline to finish the task (optional)
- [ ] 💾 **A contributor is interested** You can show interest on the task page clicking in "I'm interested" 
- [ ] 💾 **You can offer** You can make an offer
- [ ] 🔀 **You can be assigned**. You can be assigned, you should work on the task and send a Pull Request.
- [ ] 💬 **Review** Ask in comments for a review :)
- [ ] 🏁 **Approved** Once approved you will receive your payment

### 📋 Task status
- [x] ***OPEN***
- [ ] ***IN PROGRESS***
- [ ] ***DONE***

### Good to know

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. For a more compreenhensive guide to create the Pull Request properly, you can access: https://guides.github.com/activities/hello-world/

3. You can [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/)

### 🤔❓ Questions
Leave a comment below!

**Comment by leonardohof** [comment]
@alexanmtz I spent more time on this task than I thought it would. How about adding $ 25? I'll release today.

**Comment by alexanmtz** [comment]
Sounds fair @leonardohof , I reviewed your PR and you made a excellent work, just a minor change required and we are good to go 💸

**Comment by alexanmtz** [comment]
🚀 💯
