### ISSUE TITLE
The filters and tabs on task list is not opening a new tab

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#244]
On places that we have the task list like here: [https://gitpay.me/#/tasks/explore](https://gitpay.me/#/tasks/explore) we need to make the tabs and filter regular links to be able to open in a new tab (accessibility) and to be persisted as well (added on the url like https://gitpay.me/#/tasks/explore/open for open tasks, for example)

### Why
We need to improve our task list for accessibility and to persist the states of filters and tabs

### Level
Beginner

### Current behavior
When the user click on any link on the task list, like the filters (open, in progress, done) or on the tabs (created by me etc) the links not persist and if we try to open a new tab is not possible.

### Expected behavior
When the user click on any link on the task list, like the filters (open, in progress, done) or on the tabs (created by me etc) the links should persist as a different url and we should be able to open in a new tab.

### Useful links
  - https://github.com/ReactTraining/react-router

### How to solve this issue
 - Probably you will have to create new routes to handle the states
 - You will have to change the way we link using regular links, using `<Link />` from react-router

### How to reproduce the user scenario
 - Open task list explore: [https://gitpay.me/#/tasks/explore](https://gitpay.me/#/tasks/explore)

**Comment by alexanmtz** [comment]
https://gitpay.me/#/task/151

**Comment by alexanmtz** [comment]
Maybe this link could help with the issue when try to run the project on Linux:
https://github.com/mui-org/material-ui/issues/12408

**Comment by yuritoledo** [comment]
Now it's working fine on linux @alexanmtz . The mui link isn't necessary anymore!

**Comment by alexanmtz** [comment]
great @yuritoledo and the migrations is working now as well?

**Comment by yuritoledo** [comment]
Yes, the migrations are. I'd sent a message to you in Slack about another problem :/

**Comment by alexanmtz** [comment]
### 🆕 Welcome to Gitpay

Gitpay is an Open Source platform to reward contributors to get thinks done 💝

[About Gitpay platform](https://gitpay.me).

For portuguese, you can [access the portuguese version](https://github.com/worknenjoy/gitpay-github-app/blob/master/first-comment.pt-br.md)

### 📋 Step by Step

- [x] 🔔 ***Issue open*** an issue was created
- [x] 👌 **Issue added on Gitpay** this issue was added on gitpay [https://gitpay.me/#/task/151](https://gitpay.me/#/task/151)
- [x] 📝 **Add bounties** A bounty is added to get things done
- [x] 📝 **Set a deadline** A deadline to finish the task (optional)
- [x] 💾 **A contributor is interested** You can show interest on the task page clicking in "I'm interested" 
- [x] 💾 **You can offer** You can make an offer
- [x] 🔀 **You can be assigned**. You can be assigned, you should work on the task and send a Pull Request.
- [ ] 💬 **Review** Ask in comments for a review :)
- [ ] 🏁 **Approved** Once approved you will receive your payment

### 📋 Task status
- [x] ***OPEN***
- [x] ***IN PROGRESS***
- [ ] ***DONE***

### Good to know

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. For a more compreenhensive guide to create the Pull Request properly, you can access: https://guides.github.com/activities/hello-world/

3. You can [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/)

### 🤔❓ Questions
Leave a comment below!

**Comment by alexanmtz** [comment]
merged on #292
