### ISSUE TITLE
Assigned to me is showing tasks that I'm not assigned

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#264]
At [task explore](https://gitpay.me/#/tasks/explore) page, the assign to me show other tasks that I'm not the one assigned

### Level
Beginner

### Current behavior
On the task filters, when choose "Assigned to me", it shows tasks I'm not assigned

### Expected behavior
The expected behavior is shown only the tasks assigned to me

### Useful links
We use selectors to create the filters

### How to reproduce the user scenario
 - Create two users (one will create the task and other will be assigned)
 - Create two tasks importing from Github
 - The user that wish to be assigned, show interest
 - The user that created a task assign the other user
 - The user assigned, when clicked in the task explorer on the section "assigned to me" will see all the tasks

**Comment by alexanmtz** [comment]
### 🆕 Welcome to Gitpay

Gitpay is an Open Source platform to reward contributors to get thinks done 💝

[About Gitpay platform](https://gitpay.me).

For portuguese, you can [access the portuguese version](first-comment-pt-br.md)

### 📋 Step by Step

- [x] 🔔 ***Issue open*** an issue was created
- [x] 👌 **Issue added on Gitpay** this issue was added on gitpay [https://gitpay.me/#/task/204](https://gitpay.me/#/task/204)
- [ ] 📝 **Add bounties** A bounty is added to get things done
- [ ] 📝 **Set a deadline** A deadline to finish the task (optional)
- [ ] 💾 **A contributor is interested** You can show interest on the task page clicking in "I'm interested" 
- [ ] 💾 **You can offer** You can make an offer
- [ ] 🔀 **You can be assigned**. You can be assigned, you should work on the task and send a Pull Request.
- [ ] 💬 **Review** Ask in comments for a review :)
- [ ] 🏁 **Approved** Once approved you will receive your payment

### 📋 Task status
- [x] ***OPEN***
- [  ] ***IN PROGRESS***
- [  ] ***DONE***

### Good to know

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. For a more comprehensive guide to create the Pull Request properly, you can access: https://guides.github.com/activities/hello-world/

3. You can [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/)

### 🤔❓ Questions
Leave a comment below!

**Comment by alexanmtz** [comment]
Tested and merged, thanks @leonardohof 🥇 🚀
