### ISSUE TITLE
Add Github comment when an issue is added on Gitpay

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#841]
Add a comment on Github using our bot when an issue is imported to Gitpay from Github.

This is the content:
```### 🆕 Welcome to Gitpay

Gitpay is an Open Source platform to reward contributors to get things done 💝

[About Gitpay platform](https://gitpay.me).

For portuguese, you can [access the portuguese version](https://github.com/worknenjoy/gitpay-github-app/blob/master/first-comment.pt-br.md)

### 📋 Step by Step

#### If you are the task owner who created this issue
- [x] 🔔 ***Issue open*** an issue was created
- [x] 👌 **Issue added on Gitpay** this issue was added on gitpay [{{url}}]({{url}})
- [ ] 📝 **Add bounties** A bounty is added to get things done
- [ ] 📝 **Set a deadline** A deadline to finish the task (optional)
- [ ] 💾 **Choose a contributor interested** You can choose someone interested that will be able to solve your issue 

#### If you want to contribute and be rewarded
- [ ] 💾 **A contributor is interested** You can show interest on the task page clicking in "I'm interested" 
- [ ] 💾 **You can offer** You can make an offer
- [ ] 🔀 **You can be assigned**. You can be assigned, you should work on the task and send a Pull Request.
- [ ] 💬 **Review** Ask in comments for a review :)
- [ ] 🏁 **Approved** Once approved you will receive your payment

### 📋 Task status
- [x] ***OPEN***
- [ ] ***IN PROGRESS***
- [ ] ***DONE***

### Good to know

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. For a more compreenhensive guide to create the Pull Request properly, you can access: https://guides.github.com/activities/hello-world/

3. You can [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/)

### 🤔❓ Questions
Leave a comment below!
This issue was a comment made by our GitpayBot [Gitpay Bot](https://github.com/gitpaybot).
```
### Why
We will let Github users know that this given issue was imported to Gitpay.

### Level
Beginner

### Current behavior
When an issue is added, nothing happens

### Expected behavior
When an issue is added, our GithubBot should comment on that issue

### Useful links
  - Github API: https://docs.github.com/en/rest
  - Material-UI: https://material-ui.com/
  - One example: https://github.com/worknenjoy/gitpay/blob/master/modules/bot/comment.js

### How to reproduce the user scenario
- Scenario 1
   - Run the project locally
   - Create a user
   - Import an issue

### What you will need to complete this issue
You will need the development API keys to make the comments on the Github page

### Tips
- All the UI will use Material UI (https://material-ui.com/)
- Use our translation library Run `npm run translate` on the `/frontend` folder to sync translation before sending the PR
